# Generated by Django 5.0.7 on 2024-07-18 09:48

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.jpg', upload_to=myapp.models.get_image_upload_path)),
                ('processed_image', models.ImageField(blank=True, default='resized_images/default.jpg', null=True, upload_to=myapp.models.get_resized_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('license_plate_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
